[project]
name = "garbage-detector"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.75.0",
    "opencv-python>=4.11.0.86",
    "python-dotenv>=1.1.0",
    "tqdm>=4.67.1",
]
